import { Footer, Navbar, ThemeProvider } from "@/components";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
   title: "Car Hub",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="en" className="scroll-smooth" id="html">
         <body>
            <ThemeProvider
               attribute="class"
               defaultTheme="system"
               enableSystem
               disableTransitionOnChange
            >
               <Navbar />
               {children}
               <Footer />
            </ThemeProvider>
         </body>
      </html>
   );
}
